### ISSUE TITLE
Block rules

### ISSUE THREAD

**Issue by anuraag488** [hoodedpaladin/HeartGuard#1]
Hi
Can we have block rules instead of only allow rules. I would like to allow all by default and block only specific domains or apps.

Thanks

**Comment by DI555** [comment]
yep, imo should be two different rule - white list way and black list way ! and also theis combinations together, where one (white or black) set of rule is primary(master) and other one(black or white) is secondary(slave)!

**Comment by hoodedpaladin** [comment]
The intended audience for this app is people who want self-control blocking to complement Pluckeye. Allow-by-default and block rules are possible, but very low on the priority for features.
