### ISSUE TITLE
The HeartGuard App Itself In The List Of All Apps! [Feature]

### ISSUE THREAD

**Issue by DI555** [hoodedpaladin/HeartGuard#2]
well, this feature was deleting from NG long time ago, for sorrow for most their users((.
Could you please implement it again, - "show the HeartGuard app itself in the list of all apps".
Many thanks in advance!

**Comment by hoodedpaladin** [comment]
What's the point? I agree entirely with the response from this FAQ from NetGuard:
https://github.com/M66B/NetGuard/blob/master/FAQ.md#user-content-faq65

"(65) Why can NetGuard not block itself?

First of all, if NetGuard could block itself, you should trust that NetGuard really blocks itself, which is basically the same as trusting that NetGuard doesn't connect to the internet when not needed."

**Comment by DI555** [comment]
he did it just in case using by NG the gcm/fcm garbage from gp srvcs((..
it’s not the case of trustness or not, it will show and be clear that the app is in closed box or not.

**Comment by hoodedpaladin** [comment]
I don't know what gcm/fcm are.
Yes, NetGuard makes queries to the internet itself, for example, for reverse DNS lookup. But the code is all open source so I still agree with the NetGuard FAQ.
If that's the only feature you want, why don't you fork NetGuard yourself?

**Comment by DI555** [comment]
gcm/fcm is a google play servicies and google’s telemetry/tracker injector.. so, if the app is in gp store, it contains theese garbage blobs inside itself and uses it for background communications((
..and yes, NG is opensourced, it’s a good thing.

**Comment by hoodedpaladin** [comment]
This app isn't on the Google Play store, and probably never will be. Will not implement.

**Comment by hoodedpaladin** [comment]
Close as not planned.
