### ISSUE TITLE
DNS-over-HTTPS (DoH) feature

### ISSUE THREAD

**Issue by DI555** [hoodedpaladin/HeartGuard#3]
since NG was contained only unencrypted DNS support, greatly if HG will contain DNS-over-HTTPS (DoH) feature!
it’s a string integer line with entering one or more space-separated DoH template URLs.
the examples of list of some public resolvers are:
AdGuard: https://dns.adguard.com/dns-query
Cloudflare: https://cloudflare-dns.com/dns-query
Google: https://dns.google/dns-query
Quad9: https://9.9.9.9/dns-query

**Comment by hoodedpaladin** [comment]
This is just as impossible on HG as it is on NG. Closing.
